config/routes.rb
College::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  resources :sessions, only: [ :new, :destroy, :create ]
  resources :nominees, only: [ :new, :create, :show ] 

  
  root :to => "dashboard#home"
  match 'nominees' => 'nominees#new'
  match 'dashboard' => 'dashboard#show_dashboard'
  match 'about' => "dashboard#about"

  
  

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
	before_filter :require_login, :only => :show_dashboard

	# Display the home page
	def home
	end


	# Show all the general graphs and statistics
	def show_dashboard
	end


	# About page
	def about
	end

end

app/views/dashboard/about.html.erb
<div dir="rtl" class="jumbotron" id="about_page">
	<article class="content-holder container">
		<h4>
			<p>What are your chances? זו מערכת BI שמטרתה היא חיזוי הישגיו של מועמד לתואר ראשון במכללה האקדמית תל-אביב יפו. </br>
			המערכת מאפשרת מענה על מספר שאלות עיקריות המסקרנות מועמד להרשמה למכללה וכן מסקנות את המכללה עצמה בהקשר לאותו מועמד. </br>
			זאת ע"י שימוש בממשק אינטרנט פשוט בו מזינים את נתוני הבסיס של המועמד וכן את הבית ספר בו יהיה מעוניין ללמוד ובלחיצת כפתור מקבלים תוצאות המתבססות על ניתוח סטטיסטי של נתונים על הסטודנטים במכללה מ-10 השנים האחרונות. </p> 
			<p>
			<ul class="center-ul">השאלות העיקריות להן ניתן מענה:
				<li>מה סיכוייו של המועמד לסיים את התואר הראשון בבית הספר בו בחר? </li>
				<li>באיזה ציון יסיים המועמד את התואר הראשון בבית הספר בו בחר? </li>
				<li>מה סיכוייו של המועמד להמשיך לתארים מתקדמים יותר בסיומו את התואר? </li>
				<li>מה סיכוייו של המועמד לעבוד במקצוע המשתייך לתואר שלו בסיום לימודיו ? </li> 
			</ul>
			</p>
			<p>
			בנוסף לכך, האתר מאפשר לצפות ב-dashboard (לוח מכוונים) כללי על נתוני הסטודנטים (לשעבר) במכללה
			</br>ועל הקשר בין הישגיהם לבין נתוניהם ההתחלתיים. </br>
			אנו מאמינים שמערכת זו היא בסיס טוב לכניסה לעולם ניתוח נתוני קבלה וסיום וקבלת החלטות מושכלות ע"י המכללה בהתאם למה שיראו הנתונים. </br>
			בעולם בו יש כ"כ הרבה מידע והוא נגיש באמצעות הטכנולוגיה המתקדמת, ניתן להצליח יותר אם מנצלים מידע זה לטובת העסק. 
			</p>
		</h4>
	</article>
</div>

app/views/dashboard/home.html.erb
	<div class="jumbotron main-jumbotron">
	  	<div class="alert_message"><%=t alert if alert.present? %></div>
	  	<div class="container">
	    	<h1>WHAT ARE YOUR CHANCES?</h1>
	    	<p>הדרך הטובה ביותר לדעת מה הסיכויים שלך לסיים, להצליח, להתקדם... </br>
	    		אל תפחד לבדוק את העתיד!</p>
	  	</div>
  	 	<div class="container">
		  
		  <% if current_user.blank? %>  
			  <%= form_tag sessions_path do %>
			    <div class="field">
			      <%= label_tag "שם משתמש" %>
			      <%= text_field_tag :username, params[:email] %>
			    </div>
			    <div class="field">
			      <%= label_tag "ססמא" %>
			      <%= password_field_tag :password %>
			    </div>
			    <div class="field">
			      <%= check_box_tag :remember_me, 1, params[:remember_me] %>
			      <%= label_tag "זכור אותי" %>
			    </div>
			    <div class="actions"><%= submit_tag "התחבר" %></div>
			    <div class="field">
			    	
			  	</div>	
				<% end %>			
			<% end %>

		</div>
	</div>
	
</body>
</html>

app/views/dashboard/index.html.erb
<div class="jumbotron" id="index_page">
  	
	<div class="container">
  	<h2>דוחות להנאתך</h2>
	</div>


	<div class="content-holder container">
		
		<div class="row-fluid">
			<div class="span6 graph">
				<%= @bar= Gchart.bar(:data => [300, 100, 30, 200, 10, 100], :title => 'Noisy') 
				image_tag(@bar) %>
			</div>
			<div class="span6 graph">
				<%= @pie=Gchart.pie_3d(:data => [20, 35, 45], :title => 'Steamy')
				 image_tag(@pie) %>
			</div>
		</div>

		<div class="row-fluid">
			<div class="span6"></div>
			<div class="span6"></div>
		</div>

		<div class="row-fluid">
			<div class="span6 graph">
				<%= @line=Gchart.line(:data => [0, 40, 10, 70, 20], :title => 'Pretty')
				 image_tag(@line) %>
			</div>
			<div class="span6 graph">
			<%= @line=Gchart.line(:data => [0, 40, 10, 70, 20], :title => 'Smelly')
				 image_tag(@line) %>
			</div>
		</div>
	</div>
	
</div>

app/views/dashboard/show_dashboard.html.erb
<div dir="rtl" class="jumbotron" id="index_page">
  	
	<div class="content-holder container">
		
		<div class="row-fluid">
			<div id="grades_range_chart" class="span6 graph"></div>
			<div id="graduates_by_year_chart" class="span6 graph"></div>
		</div>

		<br><br><br> 

		<div class="row-fluid">
			<div id="grades_dots_chart" class="span12 graph"></div>
		</div>

		<br><br><br> 
		
		<div class="row-fluid">
			<div id="grades_by_school_chart" class="span6 graph"></div>
			<div id="job_level_chart" class="span6 graph"></div>
		</div>

		<br><br><br> 

		<div class="row-fluid">
			<div id="grades_by_range_and_by_school_chart" class="span12 graph"></div>
			<!-- <div id="some_chart" class="span12 graph"></div> -->
		</div>
	
	</div>
</div>