config/routes.rb
College::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  resources :sessions, only: [ :new, :destroy, :create ]
  resources :nominees, only: [ :new, :create, :show ] 

  
  root :to => "dashboard#home"
  match 'nominees' => 'nominees#new'
  match 'dashboard' => 'dashboard#show_dashboard'
  match 'about' => "dashboard#about"

  
  

end

app/models/nominee.rb
# == Schema Information
#
# Table name: nominees
#
#  id                 :integer          not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  age                :integer
#  city               :string(255)
#  school_grade       :integer
#  math_units         :integer
#  math_grade         :integer
#  sat_grade          :integer
#  last_result_graphs :string(255)
#  english_units      :integer
#  english_grade      :integer
#

class Nominee < ActiveRecord::Base      
	attr_accessible :age, :gender, :gender_code, :city, :city_code, :school_grade, :sat_grade,
									:math_units, :math_grade, :english_units, :english_grade, :last_result_graphs, :starting_semester, :school, :school_code, :is_working, :english_level

  	validates :age, :sat_grade, :school_grade, :math_units, :math_grade, :english_units, :english_grade, :starting_semester, :is_working, :english_level,
  					:numericality => { :greater_than_or_equal_to => 0 }

	validates_presence_of :city, :gender, :school

end

app/controllers/nominees_controller.rb
#encoding: utf-8

class NomineesController < ApplicationController
  before_filter :require_login, :only => [:new, :show, :create]
  
  def show
    @nominee = Nominee.find(params[:id])
    
    # Generate box results
    @nominee_boxes = []
    query_codes = RegressionFormula.where(school_code: @nominee.school_code).select("distinct query_code, regression_type_code, question, question_code, correlation_coefficient").order('question_code')
    query_codes.each do |f|
      next if f.question_code == 7 # Skip this one. didnt remove in db just in case..
      y = NomineesHelper.calc_formula(@nominee, f.query_code, f.regression_type_code).round(2)
      r = f.correlation_coefficient

      if f.question_code == 3 # משך תואר משוער בשנים
        y_formatted = NomineesHelper.format_degree_duration(y)
      else
        y_formatted = (y * 100).round(2).to_s + "%" if (f.regression_type_code == 9)
      end

      @nominee_boxes << [f.question, y_formatted || y.to_s, r]
    end

    # Generate charts
    @nominee_charts = []
    graph_rows = RegressionGraph.where('school_code = ? AND var_code is not null', @nominee.school_code)
    graph_rows.each do |g|
      chart = Hash.new
      x_axis_field = NomineesHelper::get_display_by_code_regressions("variable", g.var_code)
      x_title = t("views.nominee_show.#{x_axis_field}")
      chart[:tickInterval] = 1 if x_axis_field == 'starting_semester'
      chart[:x_axis] = x_title
      chart[:y_axis] = g.question 
      chart[:title] = chart[:x_axis] + " - " + chart[:y_axis]
      chart[:data_linear] = NomineesHelper.nominee_chart_data_linear(@nominee, g.query_code)
      chart[:data_dots_obs] = NomineesHelper.nominee_chart_data_dots_observations(@nominee.school_code, x_axis_field, NomineesHelper::get_tag_by_code_regressions("question", g.question_code, "y_variable"))
      chart[:data_dots_ind] = NomineesHelper.nominee_chart_data_dots_single(@nominee, g.var_code, g.query_code)
      @nominee_charts << chart
    end
  end

  # GET /nominees/new
  def new
    @nominee = Nominee.new
  end


  # POST /nominees
  # POST /nominees.json
  def create
    Rails.logger.error(params[:nominee])
    @nominee = Nominee.new(params[:nominee])

    # Get lookup values
    @nominee.city = StudentsLookup.where("field_name = 'city' and numeric_value = ? ", @nominee.city_code).first.display_name
    @nominee.gender = StudentsLookup.where("field_name = 'gender' and numeric_value = ? ", @nominee.gender_code).first.display_name
    @nominee.school = StudentsLookup.where("field_name = 'school' and numeric_value = ? ", @nominee.school_code).first.display_name
    
    if @nominee.save
      redirect_to @nominee, notice: 'Nominee was successfully created.'
    else
      render action: "new"
    end
  end

end

app/helpers/nominees_helper.rb
#encoding: utf-8

module NomineesHelper
	
	def self.get_list_by_field_students(field_name)
		rows = StudentsLookup.where('field_name = ? and display_name != \'unknown\'', field_name).order('display_name')
  	rows.map { |option| [option.display_name, option.numeric_value] }
  end

  def self.get_tag_by_code_students(field_name, code, tag_name)
    res = StudentsLookup.where("field_name = ? and numeric_value = ?", field_name, code).select(:tags).first
    res.tags.match(/#{tag_name}=([a-zA-Z0-9_]*){1};/)[1]
  end

  def self.get_tag_by_code_regressions(field_name, code, tag_name)
    res = RegressionsLookup.where("field_name = ? and id = ?", field_name, code).select(:tags).first
    res.tags.match(/#{tag_name}=([a-zA-Z0-9_]*){1};/)[1] if res.present?
  end

  def self.get_display_by_code_regressions(field_name, code)
    RegressionsLookup.where("field_name = ? and id = ?", field_name, code).first.display_name
  end

  def self.get_field_value(checked_nominee, var_code)
    var_display = self.get_display_by_code_regressions("variable", var_code)
    
    case var_display 
    when "start_studying_age"   
      var_value = checked_nominee.age
    when "is_male"  
      var_value = NomineesHelper::get_tag_by_code_students("gender", checked_nominee.gender_code, "is_male").to_i
    when "is_a_city"
      var_value = NomineesHelper::get_tag_by_code_students("city", checked_nominee.city_code, "is_a_city").to_i
    when "school_grade"
      var_value = checked_nominee.school_grade
    when "sat_grade" 
      var_value = checked_nominee.sat_grade
    when "integrated_grade"  
      var_value = (checked_nominee.sat_grade + 10 * (checked_nominee.school_grade-30))/2
    when "subject1_grade"  
      var_value = checked_nominee.math_grade
    when "subject1_units"  
      var_value = checked_nominee.math_units
    when "subject2_grade"  
      var_value = checked_nominee.english_grade
    when "subject2_units"  
      var_value = checked_nominee.english_units
    when "english_level"  
      var_value = checked_nominee.english_level
    when "is_working"  
      var_value = checked_nominee.is_working
    when "starting_semester"  
      var_value = checked_nominee.starting_semester
    else
      var_value = 0
    end

    var_value.to_i
  end


  def self.calc_formula(checked_nominee, query_code, regression_type_code)
  	query_vars = RegressionFormula.where(query_code: query_code)
  	y = 0
  	query_vars.each do |var|
  	  if (var.var_code.present?)
  	    field_value = get_field_value(checked_nominee, var.var_code)
  	    y += (field_value * var.var_coefficient) 
  	  else
  	    y += var.var_coefficient
  	  end
  	end

  	# Calc logistic regression
  	if (regression_type_code == 9)
  	  y = 1/(1+Math.exp(-y))
  	end

  	y
  end

  def self.calc_graphs(query_code)
    query_vars = RegressionFormula.where(query_code: query_code)
    y = 0
    query_vars.each do |var|
      if var.var_code.present?
        field_value = get_field_value(checked_nominee, var.var_code)
        y += (field_value * var.var_coefficient) 
      else
        y += var.var_coefficient
      end
    end

    # Calc logistic regression
    if regression_type_code == 9
      y = 1/(1+Math.exp(-y))
    end

    return y  
  end

  # Getting the data for the 1st graph. 
  def self.nominee_chart_data_linear(nominee, graph_query_code)
    # factors as in: ax + b
    a_factor = RegressionGraph.where("query_code = ? AND var_code IS NOT NULL", graph_query_code).first
    b_factor = RegressionGraph.where("query_code = ? AND var_code IS NULL", graph_query_code).first
    
    x_min = get_tag_by_code_regressions("variable", a_factor.var_code, "min_display").to_i
    x_max = get_tag_by_code_regressions("variable", a_factor.var_code, "max_display").to_i

    res = []
    res << [x_min, a_factor.var_coefficient * x_min + b_factor.var_coefficient]
    res << [x_max, a_factor.var_coefficient * x_max + b_factor.var_coefficient]

    return res
  end

  # Getting data for the dots chart - the rest of the students
  def self.nominee_chart_data_dots_observations(school_code, x_axis_field, y_axis_field)
    where = "#{x_axis_field} IS NOT NULL AND #{y_axis_field} IS NOT NULL AND graduation_school_code IS NOT NULL AND graduation_school_code = ?"
    select = "#{x_axis_field},#{y_axis_field}"
    rows = StatRow.where(where, school_code).select(select)

    rows.map { |r| [r[x_axis_field].to_f, r[y_axis_field].to_f] }
  end

  # Getting data for the dots chart - the obseravtion (one dot)
  def self.nominee_chart_data_dots_single(nominee, x_axis_field, graph_query_code)
    x_value = self.get_field_value(nominee, x_axis_field).to_f
    a_factor = RegressionGraph.where("query_code = ? AND var_code IS NOT NULL", graph_query_code).first
    b_factor = RegressionGraph.where("query_code = ? AND var_code IS NULL", graph_query_code).first

    [x_value, a_factor.var_coefficient * x_value + b_factor.var_coefficient]
  end

  def self.format_degree_duration(length)
    case length
    when 1..3
      return "עד 3 שנים"  
    when 3.01..4
      return "עד 4 שנים"  
    when 4.01..100
      return "מעל 4 שנים" 
    else
     return ""
    end 
  end
end

app/views/nominees/_form.html.erb
<div class="row nominee_section">

  <%= form_for(@nominee) do |f| %>
    
    <% if @nominee.errors.any? %>
      <div class="alert alert-error nominee_form_error" id="error_explanation">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h5>ישנן שגיאות בהזנת הפרטים</h5>
        <ul>
          <% @nominee.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>   


    <table class="table-bordered">
      <tr>
        <td> <%= Nominee.human_attribute_name("age") %> </td>
        <td> <%= f.number_field(:age, in: 10..99) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("gender") %> </td>
        <td> <%= f.select(:gender_code, options_for_select(NomineesHelper::get_list_by_field_students("gender"))) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("city") %> </td>
        <td> <%= f.select(:city_code, options_for_select(NomineesHelper::get_list_by_field_students("city"))) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("school_grade") %> </td>
        <td> <%= f.number_field(:school_grade, :in => 1...145, :step => 0.1) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("sat_grade") %> </td>
        <td> <%= f.number_field(:sat_grade, in: 300..800) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("math_units") %> </td>
        <td> <%= f.number_field(:math_units, in: 0..5) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("math_grade") %> </td>
        <td> <%= f.number_field(:math_grade, in: 0..125) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("english_units") %> </td>
        <td> <%= f.number_field(:english_units, in: 0..5) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("english_grade") %> </td>
        <td> <%= f.number_field(:english_grade, in: 0..125) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("english_level") %> </td>
        <td> <%= f.number_field(:english_level, in: 1..5) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("starting_semester") %> </td>
        <td> <%= f.number_field(:starting_semester, in: 1..2) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("is_working") %> </td>
        <td> <%= f.select(:is_working, options_for_select([["לא",0],["כן",1]])) %> </td>
      </tr>
      <tr>
        <td> <%= Nominee.human_attribute_name("school") %> </td>
        <td> <%= f.select(:school_code, options_for_select(NomineesHelper::get_list_by_field_students("school"))) %> </td>
      </tr>
      <tr class="actions nominee_form_submit">
        <td colspan="2">
            <%= f.submit :class => 'btn btn-success btn-large' %>
        </td>
      </tr>
    </table>

  <% end %>

</div>

app/views/nominees/edit.html.erb
<h1>Editing nominee</h1>

<%= render 'form' %>

<%= link_to 'Show', @nominee %> |
<%= link_to 'Back', nominees_path %>

app/views/nominees/index.html.erb
<h1>Listing nominees</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nominees.each do |nominee| %>
  <tr>
    <td><%= link_to 'Show', nominee %></td>
    <td><%= link_to 'Edit', edit_nominee_path(nominee) %></td>
    <td><%= link_to 'Destroy', nominee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nominee', new_nominee_path %>

app/views/nominees/new.html.erb
<div class="jumbotron nominee_page">

	<header class="inline">
		<h2>הזנת נתוני מועמד</h2>
		<br>
	</header>

	<div class='container'>
		<%= render 'form' %>
	</div>

<div>

app/views/nominees/show.html.erb
<script type="text/javascript" charset="utf-8">

<% @nominee_charts.each_with_index do |chart, i| %>

  $(function () {
    var chart;
    $(window).load(function() {
      chart = new Highcharts.Chart({
        chart: {
          renderTo: 'prediction_chart<%=i.to_s%>',
          plotBackgroundColor: null,
          plotBorderWidth: null,
          plotShadow: true
        },
        tooltip: {
            enabled: false
        },
        xAxis: {
            title: {
                text: '<%= chart[:x_axis] %>'
            }<% if chart[:tickInterval].present? %>,
            tickInterval: <%= chart[:tickInterval] %>,
            min: 0,
            max: 3,
            categories: ['', 'א', 'ב', '']
            <% end %>
        },
        yAxis: {
            title: {
                text: '<%= chart[:y_axis] %>'
            }<% if chart[:tickInterval].present? %>,
            labels: {
                enabled: false
            }
            <% end %>
        },
        title: {
            text: '<%= chart[:title] %>'
        },
        series: [{
            type: 'line',
            name: 'Regression Line',
            data: <%= chart[:data_linear] %>,
            marker: {
                enabled: false
            },
            states: {
                hover: {
                    lineWidth: 0
                }
            },
            enableMouseTracking: false
        }, {
            type: 'scatter',
            name: 'Observations',
            data: <%= chart[:data_dots_obs] %>,
            marker: {
                radius: 3
            }
        }, {
            type: 'scatter',
            name: 'Individual',
            data: [<%= chart[:data_dots_ind] %>],
            marker: {
                radius: 7
            }
        }]
      });
    });
  });

<% end %>
</script>


<div class="jumbotron nominee_page">  	
	<div class="content-holder container">
		
		<div class="row-fluid">
			<div class="row-fluid span10">
                <h4 class="header lead" style="text-align: center;"> מועמד ל<%= @nominee.school %> </h4>
				<% 0.upto(@nominee_charts.count - 1) do |i| %>
				<div class="row-fluid"> 
					<div id= <%="prediction_chart#{i.to_s}"%> class="nominee_section_span"></div>
				</div>
				<br><br><br><br>
				<% end %> 

                <div class="row-fluid">
                    <h4> ייתכן כי בעלי פטורים יסיימו בפחות מ-3 שנים * </h4>
                    <h4> קיים מספר גבוה של תמילדים הלומדים בסמסטר קיץ * </h4>
                </div>
			</div>

			<div class="span2">
				<% @nominee_boxes.each do |p| %>
					<div class="row-fluid thumbnail nominee_result_box">
						<h4> <%= p[0] %> </h4>
						<h3> <b> <%= p[1] %> </b> </h3>

						<div> מקדם המתאם: <%= p[2] %> </div>
					</div>
					<br><br>
				<% end %>
			</div>

		</div>

	</div>
</div>