config/routes.rb
College::Application.routes.draw do

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  resources :sessions, only: [ :new, :destroy, :create ]
  resources :nominees, only: [ :new, :create, :show ] 

  
  root :to => "dashboard#home"
  match 'nominees' => 'nominees#new'
  match 'dashboard' => 'dashboard#show_dashboard'
  match 'about' => "dashboard#about"

  
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Academit Tel-Aviv BI</title>
	  
	  <link rel="shortcut icon" type="image/png" href="brand-img.png" />
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	
	<body>
		<header>
	  	<div class="navbar navbar-inverse navbar-fixed-top navbar-inner pull-right">
				<div class="navbar-inner"/>
					<div class="container">
			    	<a class="brand" href="#" > 
						<%= image_tag "brand-img.png" %> WHAT ARE YOUR CHANCES? 
					</a>
			    	<div class="nav-collapse collapse">
						<p class="navbar-text pull-left user_logged">
							<% if current_user %>
								מחובר כ-<%= current_user.username %>
							  <%= link_to "התנתק", logout_path, { class: "navbar-link" } %>
							<% end %>
						</p>
						<ul class="nav pull-right">
					  		<%= nav_link("אודות", about_path) %>
					  		<%= nav_link("דאשבורד", dashboard_path) %>
					  		<%= nav_link("בדוק מועמד", new_nominee_path) %>
					  		<%= nav_link("ראשי", root_path) %>
						</ul>
			  		</div>
		  		</div>
				</div>
	    </div>
		</header>
		
	  <section>
			<div>	
				<!-- <p class="alert"><%= alert %></p> -->
				<!-- <p class="notice"><%= notice %></p> -->
			</div>

			<div class="main_container">
				<%= yield %>
			</div>
	  </section>

	</body>
</html>